
definitions:
  instance_and_duration: &instance_and_duration
    instance_type: mac_mini_m2
    max_build_duration: 30

  env_versions: &env_versions
      flutter: stable
      xcode: latest
      cocoapods: default

  triggering:
    merge_into_develop: &merge_into_develop
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

  scripts:
    - &install_dependencies
      name: Install Dependencies
      working_directory: app
      script: flutter pub get

    - &generate_dto_files
      name: Generate Data Transfer Objects (DTOs)
      working_directory: app
      script: dart run build_runner build -d


workflows:

  Android-Firebase-distribution-workflow:
    name: Android Firebase Distribution Workflow

    <<: *instance_and_duration
    
    triggering:
      <<: *merge_into_develop

    environment:


      <<: *env_versions

    scripts:
      - *install_dependencies

      - *generate_dto_files

          

      - name: Get the latest build number and Build the app
        working_directory: app
        script: |
          flutter build apk --release 
    publishing: 
      email:
        recipients:
          - dawitminale474@gmail.com
          - bilenmehalek7@gmail.com
          - biniyhale@gmail.com
          - tiledan2015@gmail.com
        notify:
          success: true
          failure: false


