// lib/lang/am_et.dart

import 'package:mobile/services/localization/app_string.dart';

const Map<String, String> amET = {
  // ... (previous keys)
  AppStrings.appTitle: 'የአካባቢ ማሳያ',
  AppStrings.greeting: 'ወደ መተግበሪያችን እንኳን ደህና መጡ!',
  AppStrings.languageSelect: 'እባክዎ ቋንቋዎን ይምረጡ:',
  AppStrings.welcomeLogin: 'እንኳን ደህና መጡ',
  AppStrings.login: 'ግባ',
  AppStrings.signup: 'ይመዝገቡ',
  AppStrings.forgotPassword: 'የይለፍ ቃልዎን ረሱ?',
  AppStrings.resetPassword: 'የይለፍ ቃል ዳግም ያስጀምሩ',
  AppStrings.email: 'ኢሜይል',
  AppStrings.password: 'የይለፍ ቃል',
  AppStrings.confirmPassword: 'የይለፍ ቃል አረጋግጥ',
  AppStrings.dontHaveAccount: 'መለያ የላቸውም? ',
  AppStrings.register: 'ይመዝገቡ',
  AppStrings.emailRequired: 'ኢሜይል ያስፈልጋል',
  AppStrings.passwordRequired: 'የይለፍ ቃል ያስፈልጋል',
  AppStrings.passwordMinLength: 'የይለፍ ቃል ቢያንስ 8 ቁምፊዎች መኖር አለበት',
  AppStrings.passwordUppercase: 'የይለፍ ቃል አንድ በላይ የሚገኝ ቁምፊ መኖር አለበት',
  AppStrings.passwordNumber: 'የይለፍ ቃል አንድ ቁጥር መኖር አለበት',
  AppStrings.passwordSpecialChar: 'የይለፍ ቃል አንድ ልዩ ቁምፊ መኖር አለበት',
  AppStrings.passwordMatch: 'የይለፍ ቃሎች መስማማት አለባቸው',
  AppStrings.loginSuccess: 'መግቢያ ተሳክቷል',
  AppStrings.completeDetails: 'እባክዎ ዝርዝር መረጃዎን ሙሉ ያድርጉ',
  AppStrings.selectGender: 'ጾታ ይምረጡ',
  AppStrings.firstName: 'የመጀመሪያ ስም',
  AppStrings.lastName: 'የአባት ስም',
  AppStrings.male: 'ወንድ',
  AppStrings.female: 'ሴት',
  AppStrings.enterEmailForReset: 'የይለፍ ቃል ለመሻሻል ኢሜይልዎን ያስገቡ',
  AppStrings.sendResetCode: 'የይለፍ ቃል ማስጀመሪያ ኮድ ላክ',
  AppStrings.backToLogin: 'ወደ መግቢያ ተመለስ',
  AppStrings.mediaPreview: 'ሚዲያ እንቅስቃሴ',
  AppStrings.mentionedUsers: 'የተጠቀሱ ተጠቃሚዎች',
  AppStrings.userNotFound: 'ተጠቃሚው አልተገኘም',
  AppStrings.postCreatedSuccess: 'ልጥፍ በተሳካ ሁኔታ ተፈጥሯል',
  AppStrings.postUpdatedSuccess: 'ልጥፍ በተሳካ ሁኔታ ተሻሽሏል',
  AppStrings.postDeletedSuccess: 'ልጥፍ በተሳካ ሁኔታ ተሰርዟል',
  AppStrings.postNotFound: 'ልጥፍ አልተገኘም',
  AppStrings.editPost: 'ልጥፍ አሻሽል',
  AppStrings.createPost: 'ልጥፍ ፈጥር',
  AppStrings.whatsOnYourMind: "ምን እያሰቡ ነው?",
  AppStrings.gallery: 'ገላሪ',
  AppStrings.video: 'ቪዲዮ',
  AppStrings.camera: 'ካሜራ',
  AppStrings.updatePost: 'ልጥፍ አሻሽል',
  AppStrings.changePassword: 'የይለፍ ቃል ያሻሽሉ',

  // Report Page
  AppStrings.reportPostTitle: 'ልጥፍ ሪፖርት አድርግ',
  AppStrings.reportReasonQuestion: 'ይህን ልጥፍ ለምን ሪፖርት ያደርጋሉ?',
  AppStrings.reportSubmittedSuccess: 'ሪፖርት በተሳካ ሁኔታ ቀርቧል',
  AppStrings.submitReport: 'ሪፖርት አስገባ',
  AppStrings.customReason: 'ብጁ ምክንያት',
  AppStrings.specifyReason: 'እባክዎ ይግለጹ',
  
  // Report Categories
  AppStrings.reportCatViolence: 'ዓመፅ ወይም አካላዊ ጉዳት',
  AppStrings.reportCatHateSpeech: 'የጥላቻ ንግግር ወይም ምልክቶች',
  AppStrings.reportCatHarassment: 'ትንኮሳ ወይም ጉልበተኝነት',
  AppStrings.reportCatNudity: 'እርቃንነት ወይም ወሲባዊ ይዘት',
  AppStrings.reportCatFalseInfo: 'የሐሰት መረጃ',
  AppStrings.reportCatSpam: 'አይፈለጌ መልእክት ወይም አሳሳች ይዘት',
  AppStrings.reportCatOther: 'ሌላ',

  // Report Sub-reasons
  AppStrings.subAssault: 'ጥቃት',
  AppStrings.subThreats: 'ዛቻ',
  AppStrings.subAnimalCruelty: 'የእንስሳት ጭካኔ',
  AppStrings.subRacist: 'ዘረኛ',
  AppStrings.subSexist: 'ወሲባዊ',
  AppStrings.subReligious: 'ሃይማኖታዊ',
  AppStrings.subLgbtqTargeted: 'ኤልጂቢቲኪው+ ላይ ያነጣጠረ',
  AppStrings.subRepeatedInsults: 'ተደጋጋሚ ስድብ',
  AppStrings.subNameCalling: 'ስም መጥራት',
  AppStrings.subStalking: 'ማሳደድ',
  AppStrings.subExplicitPhotos: 'ግልጽ ፎቶዎች',
  AppStrings.subSexualLanguage: 'ወሲባዊ ቋንቋ',
  AppStrings.subMedical: 'ሕክምና',
  AppStrings.subPolitical: 'ፖለቲካዊ',
  AppStrings.subOtherInfo: 'ሌላ',
  AppStrings.subClickbait: 'ክሊክባይት',
  AppStrings.subScamLinks: 'የማጭበርበሪያ አገናኞች',

  AppStrings.currentPassword: 'የአሁኑ የይለፍ ቃል',
  AppStrings.passwordUpdatedSuccess: 'የይለፍ ቃል በተሳካ ሁኔታ ተሻሽሏል',
  AppStrings.currentPasswordRequired: 'የአሁኑ የይለፍ ቃል ያስፈልጋል',
  AppStrings.newPassword: 'አዲስ የይለፍ ቃል',
  AppStrings.newPasswordRequired: 'አዲስ የይለፍ ቃል ያስፈልጋል',
  AppStrings.pleaseConfirmPassword: 'እባክዎ አዲስ የይለፍ ቃል ያረጋግጡ',
  AppStrings.passwordsDoNotMatch: 'የይለፍ ቃሎች አይጣጣሙም',

  // Navigation
  AppStrings.home: 'ቤት',
  AppStrings.reels: 'ሪልስ',
  AppStrings.notifications: 'ማስታወቂያዎች',
  AppStrings.profile: 'መገለጫ',
  AppStrings.wallet: 'የብር ቦርሳ',

  // Notifications
  AppStrings.notificationChannelName: 'አላዲያ ማስታወቂያዎች',
  AppStrings.notificationChannelDescription: 'ከአላዲያ ከቅርብ ጊዜ ዜናዎች፣ ዜናዎች እና ማስታወቂያዎች ጋር ይተውሉ።',
  AppStrings.notificationTitle: 'ርዕስ',
  AppStrings.notificationBody: 'ይዘት',

  // Chat
  AppStrings.photo: 'ፎቶ',
  AppStrings.file: 'ፋይል',
  AppStrings.cancel: 'ሰርዝ',
  AppStrings.openLink: 'አገናኝ ክፈት?',
  AppStrings.openLinkQuestion: 'ይህን አገናኝ በአሳሽዎ ውስጥ መክፈት ይፈልጋሉ?',
  AppStrings.openLinkDescription: 'ይህን አገናኝ በአሳሽዎ ውስጥ መክፈት ይፈልጋሉ?\n',
  AppStrings.yes: 'አዎ',
  AppStrings.no: 'አይ',
  AppStrings.couldNotLaunchUrl: 'URL ሊከፈት አልቻለም: ',
  AppStrings.typing: 'በመተየት ላይ...',

  // Profile
  AppStrings.followers: 'ተከታዮች',
  AppStrings.following: 'ተከትተዋል',
  AppStrings.follow: 'ተከተል',
  AppStrings.message: 'መልእክት',
  AppStrings.settings: 'ቅንብሮች',
  AppStrings.more: 'ተጨማሪ',

  // Options Page
  AppStrings.originalAudio: 'የመጀመሪያ ድምፅ',
  AppStrings.musicTrack: 'የሙዚቃ ትራክ',
  AppStrings.likes: 'የወደዱ',
  AppStrings.comments: 'አስተያየቶች',
  AppStrings.share: 'አጋራ',

  // Wallet Screen
  AppStrings.walletSettings: 'የብር ቦርሳ ቅንብሮች',
  AppStrings.buyStars: 'ኮከቦች ይግዙ',
  AppStrings.addStarsToken: 'STARS ቶከን ወደ ብር ቦርሳ ያክሉ',
  AppStrings.disconnect: 'አገናኝ ያቋርጡ',
  AppStrings.welcomeWallet: 'ወደ የተጠበቀ ብር ቦርሳ እንኳን ደህና መጡ',
  AppStrings.connectWalletMessage: 'ለመጀመር ብር ቦርሳዎን ያገናኙ።',
  AppStrings.connectWallet: 'ብር ቦርሳ ያገናኙ',
  AppStrings.connectionFailed: 'ግንኙነት አልተሳካም።',
  AppStrings.initializingWallet: 'የብር ቦርሳ አገልግሎት እያሰገነበት ነው...',
  AppStrings.initializationFailed: 'መስገንበት አልተሳካም።',
  AppStrings.token: 'ቶከን',
  AppStrings.to: 'ወደ',
  AppStrings.from: 'ከ',
  AppStrings.viewOnEtherscan: 'በ Etherscan ላይ ይመልከቱ',
  AppStrings.invalidAddress: 'የማያገለግል አድራሻ ቅርጸት',
  AppStrings.defaultRecipientNotSet: 'የነባር ተቀባይ አድራሻ አልተዘጋጅም።',
  AppStrings.invalidRecipientFormat: 'የማያገለግል የነባር ተቀባይ አድራሻ ቅርጸት።',
  AppStrings.connectSepoliaNetwork: 'ኮከቦችን ለመግዛት እባክዎ ወደ Sepolia አውታረመረብ ይገናኙ።',
  AppStrings.connectSepoliaNetworkGift: 'ኮከቦችን ለማስገባት እባክዎ ወደ Sepolia አውታረመረብ ይገናኙ።',
  AppStrings.couldNotOpenTransaction: 'የግብይት አገናኝ ሊከፈት አልቻለም።',

  // OTP Screen
  AppStrings.otpVerification: 'OTP ማረጋገጫ',
  AppStrings.enterOtpSent: 'ወደ ኢሜይልዎ የተላከውን OTP ያስገቡ',
  AppStrings.verifyOtp: 'OTP ያረጋግጡ',
  AppStrings.resendOtp: 'OTP እንደገና ይላኩ',
  AppStrings.otpSent: 'OTP በተሳካ ሁኔታ ተልኳል',
  AppStrings.otpVerificationSuccess: 'OTP ማረጋገጫ ተሳክቷል',
  AppStrings.otpVerificationFailed: 'OTP ማረጋገጫ አልተሳካም',
  AppStrings.invalidOtp: 'የማያገለግል OTP',
  AppStrings.verifying: 'እያረጋገጥን ነው...',
  AppStrings.didntReceiveCode: 'ኮድ አልተቀበሉም?',

  // Signup Validation
  AppStrings.termsAndPrivacyRequired: 'እባክዎ ውሎችን እና የግላዊነት ፖሊሲውን ይቀበሉ',
  AppStrings.nameRequired: 'የመጀመሪያ ስም ያስፈልጋል',
  AppStrings.surnameRequired: 'የአባት ስም ያስፈልጋል',
  AppStrings.emailInvalid: 'እባክዎ ትክክለኛ ኢሜይል አድራሻ ያስገቡ',
  AppStrings.passwordTooShort: 'የይለፍ ቃል ቢያንስ 8 ቁምፊዎች መኖር አለበት',
  AppStrings.passwordNoUppercase: 'የይለፍ ቃል አንድ በላይ የሚገኝ ቁምፊ መኖር አለበት',
  AppStrings.passwordNoNumber: 'የይለፍ ቃል አንድ ቁጥር መኖር አለበት',
  AppStrings.passwordNoSpecialChar: 'የይለፍ ቃል አንድ ልዩ ቁምፊ መኖር አለበት',
  AppStrings.signupSuccess: 'የመመዝገቢያ ሂደት ተሳክቷል',
  AppStrings.signupFailed: 'የመመዝገቢያ ሂደት አልተሳካም',
  AppStrings.emailAlreadyExists: 'ኢሜይል አስቀድሞ አለ',

  // Post Screen
  AppStrings.addDescription: 'መግለጫ ያክሉ...',
  AppStrings.posting: 'በማስቀመጥ ላይ...',
  AppStrings.post: 'ልጥፍ',
  AppStrings.reelPostedSuccess: 'ሪል በተሳካ ሁኔታ ተሰቅሏል!',
  AppStrings.failedToPostReel: 'ሪል ማስቀመጥ አልተሳካም: ',
  AppStrings.errorSelectingPhotos: 'ፎቶዎችን ለመምረጥ ስህተት',
  AppStrings.errorSelectingVideos: 'ቪዲዮዎችን ለመምረጥ ስህተት',
  AppStrings.errorTakingPhoto: 'ፎቶ ለመውሰድ ስህተት',
  AppStrings.addContentToPost: 'እባክዎ ለልጥፍ ይዘት ያክሉ',
  AppStrings.postingServiceUnavailable: 'የልጥፍ አገልግሎት አይገኝም',
  AppStrings.postCreationFailed: 'ልጥፍ መፍጠር አልተሳካም: ',
  AppStrings.sharePost: 'አጋራ',
  AppStrings.failedToSharePost: 'ልጥፍ ማጋራት አልተሳካም',
  AppStrings.checkOutPost: 'ይህን ልጥፍ ይመልከቱ: ',

  // Profile Settings
  AppStrings.settingsAndPrivacy: 'ቅንብሮች እና ግላዊነት',
  AppStrings.account: 'መለያ',
  AppStrings.changeProfilePicture: 'የመገለጫ ምስል ይቀይሩ',
  AppStrings.contentPreferences: 'የይዘት ምርጫዎች',
  AppStrings.supportAndAbout: 'ድጋፍ እና ስለ',
  AppStrings.termsAndPolicies: 'ውሎች እና ፖሊሲዎች',
  AppStrings.logOut: 'ውጣ',
  AppStrings.logOutConfirmation: 'እርግጠኛ ነዎት መውጣት እንደሚፈልጉ?',
  AppStrings.loggedOutSuccess: 'በተሳካ ሁኔታ ውጡ',
  AppStrings.chooseProfilePic: 'የመገለጫ ምስል ይምረጡ',
  AppStrings.update: 'አዘምን',
  AppStrings.profilePicUpdated: 'የመገለጫ ምስል ተዘምኗል!',

  // Content Preferences
  AppStrings.selectPreferences: 'ምርጫዎችዎን ይምረጡ',
  AppStrings.selectTopics: 'የሚፈልጉትን ርዕሶች ይምረጡ',
  AppStrings.personalizeExperience: 'ይህ የእርስዎን ተሞክሮ ለግል እንድናዘጋጅ ይረዳናል',
  AppStrings.continueText: 'ቀጥል',
  AppStrings.profileUpdatedSuccess: 'መገለጫ በተሳካ ሁኔታ ተዘምኗል!',
  AppStrings.failedToLoadPreferences: 'ምርጫዎችን መጫን አልተሳካም',
  AppStrings.retry: 'እንደገና ይሞከሩ',

  // User Profile
  AppStrings.gift: 'ስጦታ',

  // Search Page
  AppStrings.search: 'ፈልግ',
  AppStrings.all: 'ሁሉም',
  AppStrings.people: 'ሰዎች',
  AppStrings.posts: 'ልጥፎች',
  AppStrings.videos: 'ቪዲዮዎች',
  AppStrings.searchHint: 'ፈልግ...',
  AppStrings.noResultsFound: 'ምንም ውጤት አልተገኘም',
  AppStrings.searchPeople: 'ሰዎችን ፈልግ',
  AppStrings.searchPosts: 'ልጥፎችን ፈልግ',
  AppStrings.searchVideos: 'ቪዲዮዎችን ፈልግ',

  // Share and Gift
  AppStrings.shareTo: 'አጋራ',
  AppStrings.copyLink: 'ሊንክ ቅዳስ',
  AppStrings.linkCopied: 'ሊንክ ወደ ክሊፕቦርድ ተቅድሷል',
  AppStrings.giftStars: 'ኮከቦች ስጦታ',
  AppStrings.enterAmount: 'መጠን አስገባ',
  AppStrings.sendGift: 'ስጦታ ላክ',
  AppStrings.giftSent: 'ስጦታ በተሳካ ሁኔታ ተልኳል',
  AppStrings.giftFailed: 'ስጦታ መላክ አልተሳካም',
  AppStrings.pleaseConnectWalletToSendStarReactions: 'እባክዎ የኮከብ ስልክዎን ለመላክ ቦርሳዎን ያገናኙ።',
  AppStrings.pleaseConnectToSepoliaNetworkToGiftStars: 'ኮከቦችን ለማስገባት እባክዎ ወደ Sepolia አውታረመረብ ይገናኙ።',
  AppStrings.recipientWalletAddressNotAvailableForThisPostAuthor: 'የተቀባዩ የቦርሳ አድራሻ ለዚህ የልጥፍ ደራሲ አይገኝም።',
  AppStrings.invalidRecipientAddressFormatForThisPostAuthor: 'ለዚህ የልጥፍ ደራሲ የተቀባዩ የቦርሳ አድራሻ ቅርጸት የተሳሳተ ነው።',
  AppStrings.postAuthor: 'የልጥፍ ደራሲ',
  AppStrings.pleaseLoginToLikePosts: 'ልጥፎችን ለመውደድ እባክዎ ይግቡ',
  AppStrings.deletePost: 'ልጥፍ ሰርዝ',
  AppStrings.repostPost: 'ልጥፍ ድጋሚ አካፍል',
  AppStrings.postReposted: 'ልጥፍ ተድጋሚ ተሰቅሏል',
  AppStrings.language: 'ቋንቋ',
  AppStrings.amharic: 'አማርኛ',
  AppStrings.afaanOromo: 'አፋን ኦሮሞ',
  AppStrings.english: 'እንግሊዝኛ',
  AppStrings.selectLanguage: 'ቋንቋ ይምረጡ',

  AppStrings.waitingForVideoDuration: 'ቪዲዮ ጊዜ ለመጠበቅ እየቆየ ነው...',
  AppStrings.postUpdateFailed: 'የልጥፍ አዘምን አልተሳካም: ',

  AppStrings.invalidEmail: 'የተሳሳተ ኢሜይል አድራሻ',
};
