// lib/lang/en_us.dart

import 'package:mobile/services/localization/app_string.dart';

const Map<String, String> enUS = {
  // ... (previous keys)
  AppStrings.appTitle: 'Localization Demo',
  AppStrings.greeting: 'Welcome to our App!',
  AppStrings.languageSelect: 'Please select your language:',
  AppStrings.welcomeLogin: 'Welcome Back',
  AppStrings.login: 'Login',
  AppStrings.signup: 'Sign Up',
  AppStrings.forgotPassword: 'Forgot Password?',
  AppStrings.resetPassword: 'Reset Password',
  AppStrings.email: 'Email',
  AppStrings.password: 'Password',
  AppStrings.confirmPassword: 'Confirm Password',
  AppStrings.dontHaveAccount: 'Don\'t have an account? ',
  AppStrings.register: 'Register',
  AppStrings.emailRequired: 'Email is required',
  AppStrings.passwordRequired: 'Password is required',
  AppStrings.passwordMinLength: 'Password must be at least 8 characters',
  AppStrings.passwordUppercase: 'Password must contain at least one uppercase letter',
  AppStrings.passwordNumber: 'Password must contain at least one number',
  AppStrings.passwordSpecialChar: 'Password must contain at least one special character',
  AppStrings.passwordMatch: 'Passwords must match',
  AppStrings.loginSuccess: 'Login successful',
  AppStrings.completeDetails: 'Please complete your details',
  AppStrings.selectGender: 'Select Gender',
  AppStrings.firstName: 'First Name',
  AppStrings.lastName: 'Last Name',
  AppStrings.male: 'Male',
  AppStrings.female: 'Female',
  AppStrings.enterEmailForReset: 'Enter your email to receive a password reset code',
  AppStrings.sendResetCode: 'Send Reset Code',
  AppStrings.backToLogin: 'Back to Login',
  AppStrings.mediaPreview: 'Media Preview',
  AppStrings.mentionedUsers: 'Mentioned Users',
  AppStrings.userNotFound: 'User not found',
  AppStrings.postCreatedSuccess: 'Post created successfully',
  AppStrings.postUpdatedSuccess: 'Post updated successfully',
  AppStrings.postDeletedSuccess: 'Post deleted successfully',
  AppStrings.postNotFound: 'Post not found',
  AppStrings.editPost: 'Edit Post',
  AppStrings.createPost: 'Create Post',
  AppStrings.whatsOnYourMind: "What's on your mind?",
  AppStrings.gallery: 'Gallery',
  AppStrings.video: 'Video',
  AppStrings.camera: 'Camera',
  AppStrings.updatePost: 'Update Post',
  AppStrings.changePassword: 'Change Password',

  // Report Page
  AppStrings.reportPostTitle: 'Report Post',
  AppStrings.reportReasonQuestion: 'Why are you reporting this post?',
  AppStrings.reportSubmittedSuccess: 'Report submitted successfully',
  AppStrings.submitReport: 'Submit Report',
  AppStrings.customReason: 'Custom Reason',
  AppStrings.specifyReason: 'Please specify',
  
  // Report Categories
  AppStrings.reportCatViolence: 'Violence or Physical Harm',
  AppStrings.reportCatHateSpeech: 'Hate Speech or Symbols',
  AppStrings.reportCatHarassment: 'Harassment or Bullying',
  AppStrings.reportCatNudity: 'Nudity or Sexual Content',
  AppStrings.reportCatFalseInfo: 'False Information',
  AppStrings.reportCatSpam: 'Spam or Misleading Content',
  AppStrings.reportCatOther: 'Other',

  // Report Sub-reasons
  AppStrings.subAssault: 'Assault',
  AppStrings.subThreats: 'Threats',
  AppStrings.subAnimalCruelty: 'Animal cruelty',
  AppStrings.subRacist: 'Racist',
  AppStrings.subSexist: 'Sexist',
  AppStrings.subReligious: 'Religious',
  AppStrings.subLgbtqTargeted: 'LGBTQ+ targeted',
  AppStrings.subRepeatedInsults: 'Repeated insults',
  AppStrings.subNameCalling: 'Name calling',
  AppStrings.subStalking: 'Stalking',
  AppStrings.subExplicitPhotos: 'Explicit photos',
  AppStrings.subSexualLanguage: 'Sexual language',
  AppStrings.subMedical: 'Medical',
  AppStrings.subPolitical: 'Political',
  AppStrings.subOtherInfo: 'Other',
  AppStrings.subClickbait: 'Clickbait',
  AppStrings.subScamLinks: 'Scam links',

  AppStrings.currentPassword: 'Current Password',
  AppStrings.passwordUpdatedSuccess: 'Password updated successfully',
  AppStrings.currentPasswordRequired: 'Current password is required',
  AppStrings.newPassword: 'New Password',
  AppStrings.newPasswordRequired: 'New password is required',
  AppStrings.pleaseConfirmPassword: 'Please confirm your new password',
  AppStrings.passwordsDoNotMatch: 'Passwords do not match',

  // Navigation
  AppStrings.home: 'Home',
  AppStrings.reels: 'Reels',
  AppStrings.notifications: 'Notifications',
  AppStrings.profile: 'Profile',
  AppStrings.wallet: 'Wallet',

  // Notifications
  AppStrings.notificationChannelName: 'Aladia Alerts',
  AppStrings.notificationChannelDescription: 'Stay informed with the latest updates, news, and alerts from Aladia.',
  AppStrings.notificationTitle: 'title',
  AppStrings.notificationBody: 'body',

  // Chat
  AppStrings.photo: 'Photo',
  AppStrings.file: 'File',
  AppStrings.cancel: 'Cancel',
  AppStrings.openLink: 'Open Link?',
  AppStrings.openLinkQuestion: 'Do you want to open this link in your browser?',
  AppStrings.openLinkDescription: 'Do you want to open this link in your browser?\n',
  AppStrings.yes: 'Yes',
  AppStrings.no: 'No',
  AppStrings.couldNotLaunchUrl: 'Could not launch URL: ',
  AppStrings.typing: 'typing...',

  // Profile
  AppStrings.followers: 'Followers',
  AppStrings.following: 'Following',
  AppStrings.follow: 'Follow',
  AppStrings.message: 'Message',
  AppStrings.settings: 'Settings',
  AppStrings.more: 'More',

  // Options Page
  AppStrings.originalAudio: 'Original Audio',
  AppStrings.musicTrack: 'some music track',
  AppStrings.likes: 'likes',
  AppStrings.comments: 'comments',
  AppStrings.share: 'share',

  // Wallet Screen
  AppStrings.walletSettings: 'Wallet Settings',
  AppStrings.buyStars: 'Buy Stars',
  AppStrings.addStarsToken: 'Add STARS Token to Wallet',
  AppStrings.disconnect: 'Disconnect',
  AppStrings.welcomeWallet: 'Welcome to the Secure Wallet',
  AppStrings.connectWalletMessage: 'Connect your wallet to get started.',
  AppStrings.connectWallet: 'Connect Wallet',
  AppStrings.connectionFailed: 'Connection failed.',
  AppStrings.initializingWallet: 'Initializing wallet service...',
  AppStrings.initializationFailed: 'Initialization failed.',
  AppStrings.token: 'Token',
  AppStrings.to: 'To',
  AppStrings.from: 'From',
  AppStrings.viewOnEtherscan: 'View on Etherscan',
  AppStrings.invalidAddress: 'Invalid address format',
  AppStrings.defaultRecipientNotSet: 'Default recipient address not set.',
  AppStrings.invalidRecipientFormat: 'Invalid default recipient address format.',
  AppStrings.connectSepoliaNetwork: 'Please connect to Sepolia network to buy stars.',
  AppStrings.connectSepoliaNetworkGift: 'Please connect to Sepolia network to gift stars.',
  AppStrings.couldNotOpenTransaction: 'Could not open transaction link.',

  // OTP Screen
  AppStrings.otpVerification: 'OTP Verification',
  AppStrings.enterOtpSent: 'Enter the OTP sent to your email',
  AppStrings.verifyOtp: 'Verify OTP',
  AppStrings.resendOtp: 'Resend OTP',
  AppStrings.otpSent: 'OTP sent successfully',
  AppStrings.otpVerificationSuccess: 'OTP verification successful',
  AppStrings.otpVerificationFailed: 'OTP verification failed',
  AppStrings.invalidOtp: 'Invalid OTP',
  AppStrings.verifying: 'Verifying...',
  AppStrings.didntReceiveCode: 'Didn\'t receive code?',

  // Signup Validation
  AppStrings.termsAndPrivacyRequired: 'Please accept the terms and privacy policy',
  AppStrings.nameRequired: 'First name is required',
  AppStrings.surnameRequired: 'Last name is required',
  AppStrings.emailInvalid: 'Please enter a valid email address',
  AppStrings.passwordTooShort: 'Password must be at least 8 characters',
  AppStrings.passwordNoUppercase: 'Password must contain an uppercase letter',
  AppStrings.passwordNoNumber: 'Password must contain a number',
  AppStrings.passwordNoSpecialChar: 'Password must contain a special character',
  AppStrings.signupSuccess: 'Signup successful',
  AppStrings.signupFailed: 'Signup failed',
  AppStrings.emailAlreadyExists: 'Email already exists',

  // Post Screen
  AppStrings.addDescription: 'Add description...',
  AppStrings.posting: 'Posting...',
  AppStrings.post: 'Post',
  AppStrings.reelPostedSuccess: 'Reel posted successfully!',
  AppStrings.failedToPostReel: 'Failed to post reel: ',
  AppStrings.errorSelectingPhotos: 'Error selecting photos',
  AppStrings.errorSelectingVideos: 'Error selecting videos',
  AppStrings.errorTakingPhoto: 'Error taking photo',
  AppStrings.addContentToPost: 'Please add some content to post',
  AppStrings.postingServiceUnavailable: 'Posting service unavailable',
  AppStrings.postCreationFailed: 'Post creation failed: ',
  AppStrings.sharePost: 'Share',
  AppStrings.failedToSharePost: 'Failed to share post',
  AppStrings.checkOutPost: 'Check out this post: ',

  // Profile Settings
  AppStrings.settingsAndPrivacy: 'Settings and Privacy',
  AppStrings.account: 'Account',
  AppStrings.changeProfilePicture: 'Change Profile Picture',
  AppStrings.contentPreferences: 'Content preferences',
  AppStrings.supportAndAbout: 'Support & about',
  AppStrings.termsAndPolicies: 'Terms and Policies',
  AppStrings.logOut: 'Log Out',
  AppStrings.logOutConfirmation: 'Are you sure you want to log out?',
  AppStrings.loggedOutSuccess: 'Logged out successfully',
  AppStrings.chooseProfilePic: 'Choose profile pic',
  AppStrings.update: 'Update',
  AppStrings.profilePicUpdated: 'Profile picture updated!',

  // Content Preferences
  AppStrings.selectPreferences: 'Select Your Preferences',
  AppStrings.selectTopics: 'Select topics you\'re interested in',
  AppStrings.personalizeExperience: 'This will help us personalize your experience',
  AppStrings.continueText: 'Continue',
  AppStrings.profileUpdatedSuccess: 'Profile updated successfully!',
  AppStrings.failedToLoadPreferences: 'Failed to load preferences',
  AppStrings.retry: 'Retry',

  // User Profile
  AppStrings.gift: 'Gift',

  // Search Page
  AppStrings.search: 'Search',
  AppStrings.all: 'All',
  AppStrings.people: 'People',
  AppStrings.posts: 'Posts',
  AppStrings.videos: 'Videos',
  AppStrings.searchHint: 'Search...',
  AppStrings.noResultsFound: 'No results found',
  AppStrings.searchPeople: 'Search People',
  AppStrings.searchPosts: 'Search Posts',
  AppStrings.searchVideos: 'Search Videos',

  // Share and Gift
  AppStrings.shareTo: 'Share to',
  AppStrings.copyLink: 'Copy Link',
  AppStrings.linkCopied: 'Link copied to clipboard',
  AppStrings.giftStars: 'Gift Stars',
  AppStrings.enterAmount: 'Enter amount',
  AppStrings.sendGift: 'Send Gift',
  AppStrings.giftSent: 'Gift sent successfully',
  AppStrings.giftFailed: 'Failed to send gift',
  AppStrings.pleaseConnectWalletToSendStarReactions: 'Please connect your wallet to send star reactions.',
  AppStrings.pleaseConnectToSepoliaNetworkToGiftStars: 'Please connect to Sepolia network to gift stars.',
  AppStrings.recipientWalletAddressNotAvailableForThisPostAuthor: 'Recipient wallet address not available for this post author.',
  AppStrings.invalidRecipientAddressFormatForThisPostAuthor: 'Invalid recipient address format for this post author.',
  AppStrings.postAuthor: 'Post Author',
  AppStrings.pleaseLoginToLikePosts: 'Please login to like posts',
  AppStrings.deletePost: 'Delete Post',
  AppStrings.repostPost: 'Repost Post',
  AppStrings.postReposted: 'Post reposted',

  // Language Setting UI
  AppStrings.language: 'Language',
  AppStrings.amharic: 'Amharic',
  AppStrings.afaanOromo: 'Afaan Oromo',
  AppStrings.english: 'English',
  AppStrings.selectLanguage: 'Select Language',

  AppStrings.waitingForVideoDuration: 'Waiting for video duration...',
  AppStrings.postUpdateFailed: 'Post update failed: ',
};
