// lib/lang/en_us.dart

import 'package:mobile/services/localization/app_text.dart';

const Map<String, String> enUS = {
  // ... (previous keys)
  AppStrings.appTitle: 'Localization Demo',
  AppStrings.greeting: 'Welcome to our App!',
  AppStrings.languageSelect: 'Please select your language:',
  AppStrings.welcomeLogin: 'Welcome back! Please login to continue',
  AppStrings.login: 'Login',
  AppStrings.signup: 'Sign Up',
  AppStrings.forgotPassword: 'Forgot Password?',
  AppStrings.resetPassword: 'Reset Password',
  AppStrings.email: 'Email',
  AppStrings.password: 'Password',
  AppStrings.confirmPassword: 'Confirm Password',
  AppStrings.dontHaveAccount: 'Don\'t have an account?',
  AppStrings.register: 'Register',
  AppStrings.emailRequired: 'Email is required',
  AppStrings.passwordRequired: 'Password is required',
  AppStrings.passwordMinLength: 'Password must be at least 8 characters',
  AppStrings.passwordUppercase: 'Password must contain an uppercase letter',
  AppStrings.passwordNumber: 'Password must contain a number',
  AppStrings.passwordSpecialChar: 'Password must contain a special character',
  AppStrings.passwordMatch: 'Password and Confirm Password must match',
  AppStrings.loginSuccess: 'Login successful',
  AppStrings.completeDetails: 'Please complete your details',
  AppStrings.selectGender: 'Please select',
  AppStrings.firstName: 'First Name',
  AppStrings.lastName: 'Last Name',
  AppStrings.male: "Male",
  AppStrings.female: "Female",
  AppStrings.enterEmailForReset: 'Enter your email to receive a password reset code',
  AppStrings.sendResetCode: 'Send Reset Code',
  AppStrings.backToLogin: 'Back to Login',
  AppStrings.mediaPreview: 'Media Preview',
  AppStrings.mentionedUsers: 'Mentioned Users',
  AppStrings.userNotFound: 'User not found',
  AppStrings.postCreatedSuccess: 'Post created successfully',
  AppStrings.postUpdatedSuccess: 'Post updated successfully',
  AppStrings.postDeletedSuccess: 'Post deleted successfully',
  AppStrings.postNotFound: 'Post not found',
  AppStrings.editPost: 'Edit Post',
  AppStrings.createPost: 'Create Post',
  AppStrings.whatsOnYourMind: "What's on your mind?",
  AppStrings.gallery: 'Gallery',
  AppStrings.video: 'Video',
  AppStrings.camera: 'Camera',
  AppStrings.updatePost: 'Update Post',
  AppStrings.changePassword: 'Change Password',

  // Report Page
  AppStrings.reportPostTitle: 'Report Post',
  AppStrings.reportReasonQuestion: 'Why are you reporting this post?',
  AppStrings.reportSubmittedSuccess: 'Report submitted successfully',
  AppStrings.submitReport: 'Submit Report',
  AppStrings.customReason: 'Custom Reason',
  AppStrings.specifyReason: 'Please specify',
  
  // Report Categories
  AppStrings.reportCatViolence: 'Violence or Physical Harm',
  AppStrings.reportCatHateSpeech: 'Hate Speech or Symbols',
  AppStrings.reportCatHarassment: 'Harassment or Bullying',
  AppStrings.reportCatNudity: 'Nudity or Sexual Content',
  AppStrings.reportCatFalseInfo: 'False Information',
  AppStrings.reportCatSpam: 'Spam or Misleading Content',
  AppStrings.reportCatOther: 'Other',

  // Report Sub-reasons
  AppStrings.subAssault: 'Assault',
  AppStrings.subThreats: 'Threats',
  AppStrings.subAnimalCruelty: 'Animal cruelty',
  AppStrings.subRacist: 'Racist',
  AppStrings.subSexist: 'Sexist',
  AppStrings.subReligious: 'Religious',
  AppStrings.subLgbtqTargeted: 'LGBTQ+ targeted',
  AppStrings.subRepeatedInsults: 'Repeated insults',
  AppStrings.subNameCalling: 'Name calling',
  AppStrings.subStalking: 'Stalking',
  AppStrings.subExplicitPhotos: 'Explicit photos',
  AppStrings.subSexualLanguage: 'Sexual language',
  AppStrings.subMedical: 'Medical',
  AppStrings.subPolitical: 'Political',
  AppStrings.subOtherInfo: 'Other',
  AppStrings.subClickbait: 'Clickbait',
  AppStrings.subScamLinks: 'Scam links',

  AppStrings.currentPassword: 'Current Password',
  AppStrings.passwordUpdatedSuccess: 'Password updated successfully',
  AppStrings.currentPasswordRequired: 'Current password is required',
  AppStrings.newPassword: 'New Password',
  AppStrings.newPasswordRequired: 'New password is required',
  AppStrings.pleaseConfirmPassword: 'Please confirm your new password',
  AppStrings.passwordsDoNotMatch: 'Passwords do not match',
};
